spring:
  application:
    name: pruebatecnica

  datasource:
    url: jdbc:h2:mem:vehicles:db
    username: sa
    password: 
  
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      auto-ddl: none
    show-sql: true
    properties:
      hibernate:
      format-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  
  server:
    port: 8080
